server:  
  port: ${PORT:8082}

spring:  
  application:
    name: available-hotels
      
ribbon:
  eureka:
    enabled: true
    
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8080}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2