server:  
  port: ${PORT:8080}

spring:  
  application:
    name: available-hotels
      
ribbon:
  eureka:
    enabled: true
    
eureka:  
  client:
    serviceUrl:
      defaultZone: https://beam-hotels-discovery.herokuapp.com:8080/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
